### ISSUE TITLE
Links to authors of non-english articles is 404.

### ISSUE THREAD

**Issue by millertiga** [polylang/polylang#243] opened 2018-04-04 09:36 UTC
![image](https://user-images.githubusercontent.com/21698240/38300098-7ce3087e-382e-11e8-8d6e-6fd13407b032.png)

How can I set up to have the correct page?

**Comment by Chouby** [comment] 2018-04-10 07:56
This works for me. I am sorry but I don't understand what you want to demonstrate with your screenshot. For a bug report, I need that you answer to all questions you removed fom the issue template and also exact steps to reproduce the issue. If I don't reproduce the issue, I can't fix a bug. If this is not a bug report but a support request, please use the community supported forum and close this issue.

**Closed** 2018-05-02 14:36 UTC
Labels: Reporter feedback
