### ISSUE TITLE
Feature request: Only display menu location for the active language

### ISSUE THREAD

**Issue by wpsumo** [polylang/polylang#1037] opened 2022-05-03 11:17 UTC
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Feature request

I think this is the right place to submit this as its not a usage question rather a usage feature improvement.

Would like to make better UI by not display all menus and menus locations once switching language in polylang in wp-admin. Right now we see 8x menu and x8 location if we have 8 languages it make sense to do once show all. This when Display location and select menu to edit. But once I set Canada I should only see these ones. Right now it only change what pages we have to add to menu. But above suggestion would make it easier to work with several of menus on several of languages wordpress sites.

The only time we should see all is once we select all languages in polylang menu in wp-admin.

**Comment by Chouby** [comment] 2022-06-22 16:06
Thanks for the suggestion. This looks like a duplicate of #286

**Closed by Chouby** 2022-06-22 16:06 UTC
Labels: duplicate
