### ISSUE TITLE
All tags are attached to a post on save, if tags are set hierarchical

### ISSUE THREAD

**Issue by koskinenaa** [polylang/polylang#1385] opened 2023-11-16 09:51 UTC
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. WP 6.4.1, Polylang 3.6-dev / 3.5.2, Twenty Nineteen 2.7 
2. Add the following code to `functions.php`
3. Create n amount of tags
4. Add 1 tag to a new post or to an existing post

```
add_filter( 'register_taxonomy_args', 'provide_hierarchical_tags', 10, 2 );
function provide_hierarchical_tags(array $args, string $taxonomy): array {
	if ('post_tag' !== $taxonomy) {
		return $args;
	}

	global $wp_rewrite;

	$args['hierarchical'] = true;
	$args['rewrite'] = [
		'hierarchical' => false,
		'slug' => get_option('tag_base') ? get_option('tag_base') : 'tag',
		'with_front' => ! get_option('tag_base') || $wp_rewrite->using_index_permalinks(),
		'ep_mask' => EP_TAGS,
	];

	return $args;
}
```

## Expected behavior and actual behavior

When I follow those steps, all available tags are attached to the post.

I was expecting that only the selected tag would have been attached to the post.

**Comment by Chrystll** [comment] 2023-12-12 16:09
I cannot reproduce the issue where "all available tags are attached to the post."

I tested it on my end with your code, using only WordPress, and the hierarchical tags selected remain checked after saving in both Classic and Block editors.

**In Classic Editor + Polylang 3.5.3:**
My tags list is:
- My tag (parent)
- - tag child (child)
- News (another tag)

With Polylang, the selected hierarchical tags stay checked in the post after saving in Classic Editor mode. However, if I check only one tag, for example, the parent, then the child tag also gets selected after saving. Another observed behavior in a post: if I check "News" as one tag, then my parent tag "My tag" and my child tag "tag child" automatically get checked.

**In Block Editor + Polylang 3.5.3:**
I assume you're using the Block Editor mode?
In this configuration, everything seems to be working fine, and I'm not encountering any issues. Please see my video: [Link to the video](https://www.loom.com/share/c0851b5fffb14d96a272d8a5b547a71d?sid=8414e660-ec57-408d-a419-057730c2369a)

Could you please update to version 3.5.3 and verify if the issue still persists?

**Comment by koskinenaa** [comment] 2023-12-12 17:56
Yes, I'm using the Block Editor. Here's [a brief screen capture video](https://www.youtube.com/watch?v=AKSmpbiaIas) showing my local WP setup, versions and settings, and the issue.

I first encountered this bug on a production client site, but I'm able to reproduce it consistently in my bare-bones local WP.

**Comment by Chouby** [comment] 2024-02-04 22:19
I don't reproduce your issue when I test an install with your code. I however experience a different issue: The tags are never assigned to posts. I also noticed as in your video that WordPress mixes the labels and replaces "Tags" by "Categories".

However, I don't think we should consider this as Polylang bug and support this (I mean continuously testing) because you are indeed unintentionally creating a bug by transforming post tags to a hierarchical taxonomy and you don't need Polylang to reproduce this bug (it just happens that Polylang helped revealing the bug).

On a fresh install:
1. Create a tag with the name 'Test' .
2. Create a simple post (look at its post ID that I will call  `$post_id`). 
3. Execute : `wp_set_post_tags( $post_id, 'Test' );`.
This assigns the tag 'Test' to the post as expected from the [function doc](https://developer.wordpress.org/reference/functions/wp_set_post_tags/).

Now add your code to the WP install and renew the experience. The tag is not assigned. 

If you need a second hierarchical taxonomy beside categories, the best is probably to create a brand new custom taxonomy with a different name from core taxonomies.

That said, for another reason, I just opened a PR in which I removed our call to `wp_set_post_tags()` with names passed as param, replacing it by a call to `wp_set_post_terms()` with term ids as param. This fixes the issue that I experience with your code. This *may* also fix your issue.

**Closed by Chouby** 2024-02-04 22:19 UTC
Labels: invalid
