### ISSUE TITLE
Warning in the plugin settings sections

### ISSUE THREAD

**Issue by mrleemon** [polylang/polylang#438] opened 2020-01-10 09:14 UTC
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Set `define('WP_DEBUG', true);`
2. Activate and configure Polylang
3. Head to any of the plugin settings sections of the Polylang plugin

## Expected behavior and actual behavior

When I follow those steps, I see...

`Notice: Trying to access array offset on value of type null in /xxxxxx/wp-content/plugins/polylang/settings/settings-browser.php on line 41`

I was expecting...

No warning

**Comment by manooweb** [comment] 2020-01-24 16:09
Hello @mrleemon,
I don't reproduce the case with Polylang 2.6.9 and neither with WP 5.2.5 nor WP 5.3.2

Polylang is the only plugin activated - no mu-plugins and no other plugins activated.

The notice you have is very strange. In fact the code which triggers the notice you sent to us test an mandatory option of Polylang: `force_lang`

See https://github.com/polylang/polylang/blob/master/settings/settings-browser.php#L41

An this option such as all important options of Polylang is set when the plugin is activated
See 
- https://github.com/polylang/polylang/blob/master/install/install.php#L113
- https://github.com/polylang/polylang/blob/master/install/install.php#L80-L96

I think something went wrong in your database that makes this option doesn't exist anymore.

Could you please try on a fresh WordPress install, install only Polylang and activate it?

On your environment where the issue happens you can:
- deactivate Polylang
- in the wp_options database table delete the record with `polylang` option_name
- activate Polylang which will recreate correctly the `polylang` option_name in the database

Thanks

**Comment by mrleemon** [comment] 2020-01-25 00:06
I followed the steps at the end of your post and the issue still persists. It's strange because the `force_lang` is there:

`a:14:{s:7:"browser";b:0;s:7:"rewrite";i:1;s:12:"hide_default";i:1;s:10:"force_lang";i:1;s:13:"redirect_lang";i:1;s:13:"media_support";b:0;s:9:"uninstall";i:0;s:4:"sync";a:11:{i:0;s:10:"taxonomies";i:1;s:9:"post_meta";i:2;s:14:"comment_status";i:3;s:11:"ping_status";i:4;s:12:"sticky_posts";i:5;s:9:"post_date";i:6;s:11:"post_format";i:7;s:11:"post_parent";i:8;s:17:"_wp_page_template";i:9;s:10:"menu_order";i:10;s:13:"_thumbnail_id";}s:10:"post_types";a:1:{i:0;s:7:"exhibit";}s:10:"taxonomies";a:2:{i:0;s:16:"exhibit_category";i:1;s:11:"exhibit_tag";}s:7:"domains";a:0:{}s:7:"version";s:5:"2.6.9";s:16:"first_activation";i:1579910609;s:12:"default_lang";s:2:"es";}`

**Comment by mrleemon** [comment] 2020-01-25 00:08
I have another site in the same server and it shows the same warning, too. It's weird because I use Polylang in other sites in other hostings and I have no problems.

**Comment by mrleemon** [comment] 2020-01-25 00:20
Apparently, this warning only appears when I use PHP 7.4. I downgraded to PHP 7.3 and the warning no longer shows up.

**Comment by mrleemon** [comment] 2020-01-25 00:40
It can be fixed for PHP 7.4 changing the line to:

`return ( is_array( $this->options ) && ( 3 > $this->options['force_lang'] ) ) || class_exists( 'PLL_Xdata_Domain', true );`

Here's the PHP SRC PR:
https://github.com/php/php-src/pull/4386

**Comment by manooweb** [comment] 2020-01-27 14:12
Thanks @mrleemon 
Indeed with WordPress 5.3 and greater which support PHP 7.4 our code are not compatible here although we've already corrected some things.
See 
- https://github.com/polylang/polylang/commit/28c293e673a469c7c9cef3879381d60412e0401c
- https://github.com/polylang/polylang/commit/31de3378e14b9a1374dfd11e3d33585324fe3e4f

In fact in the current case it is because the `options` property in the PLL_Settings_Browser class isn't initialized at the right moment when we want to use it in the `is_available` method.
This property is initialized by calling the PLL_Settings_Module parent constructor which is too late.

We think it is preferable to initialize correctly this property than test its validity as you propose even if we assign its value twice.

See our PR https://github.com/polylang/polylang/pull/444

Regards

**Closed** 2020-01-27 16:29 UTC
Labels: bug

**Comment by mrleemon** [comment] 2020-01-27 17:49
Thanks!
