### ISSUE TITLE
Polylang and no more available reusable blocks menu

### ISSUE THREAD

**Issue by paolosax** [polylang/polylang#437] opened 2020-01-01 11:23 UTC
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Create a block in the page/post editor
2. Click on the block menu
3. Reusable block feature no more available

## Expected behavior and actual behavior

When I follow those steps, I can't access no more to the reusable block features directly from the block I'va just created.

I was expecting that this feature was still available

Hello,
I've just noticed that Polylang plugin disable the reusable block feature from the blocks toolbar menu list. I mean: the Wordpress reusable block functionality is still available, but it's only accessible through the Wordpress Tools&Options "Manage all the reusable blocks (* note: I'm translating from the Italian, so I don't know exactly what's the relative english menu name is). 

So, when I create a block directly in the editor of a page/post that I'd like to use as reusable, I can't do that.

(I've deactivated all the plugins that I've installed and the only one that cause the problem is Polylang. Wordpress version is 5.3.2)

Regards
Paolo

**Comment by manooweb** [comment] 2020-01-24 16:22
Hello @paolosax,

Could you provide us some screenshots to illustrate what you mean?

Please keep all the WordPress context on screenshots: menu on the left and admin bar on top.

I tested on my side both with WordPress 5.2.5 and 5.3.2 and Polylang 2.6.9 and everything seems good.

Thanks

**Comment by bartczyz** [comment] 2020-02-27 09:22
Hello @manooweb,

I'm experiencing the same issue. The problem is that when you create a new reusable block the language is not assigned to it. So:

1. Select a language from the top menu and start creating new post, add some content and save it as a reusable block.
![polylang_reusable_blocks_issue_1](https://user-images.githubusercontent.com/1191500/75429130-937aba80-5949-11ea-84cf-96fa2d35235a.gif)

2. Now when you add a new post the reusable block should be available, but it's not.
![polylang_reusable_blocks_issue_2](https://user-images.githubusercontent.com/1191500/75429347-ef454380-5949-11ea-9509-acedd908d809.gif)

3. Now when I go to "Manage all reusable blocks" (using the language I used to create the reusable block) it's not there.
![polylang_reusable_blocks_issue_3](https://user-images.githubusercontent.com/1191500/75429590-5105ad80-594a-11ea-8af3-d0fd03b4cde4.gif)

4. When I switch to "Show all languages" my reusable block shows up! But as you can see it's not assigned to any language.
![polylang_reusable_blocks_issue_4](https://user-images.githubusercontent.com/1191500/75429700-7f838880-594a-11ea-9c09-655a1d9fdf00.gif)

5. When I edit it, select a language and save it then a language gets assigned to the reusable block.
![polylang_reusable_blocks_issue_5](https://user-images.githubusercontent.com/1191500/75429838-b3f74480-594a-11ea-9fe4-b89e646a56b9.gif)

6. Now when I go and add new post the reusable block is visible!
![polylang_reusable_blocks_issue_6](https://user-images.githubusercontent.com/1191500/75429936-de490200-594a-11ea-892e-680324c56d2f.gif)

I hope that helps!

**Comment by manooweb** [comment] 2020-02-27 17:14
Thank you @bartczyz for the detailed informations.
The problem doesn't come from the use or not of the admin language switcher.

In fact reusable blocks are really translatable. The problem come from resuable block creation in another post type editing because the save request for the reusable block consider that it is the request for the post type that we are editing (post, page ...) where the lang is a post type attribute. Then the language isn't sent in the request in this precise case.

I'm taking a look to find the best solution to be sure we are in the right situation. Indeed reusable blocks can be used in a wp_block post type edit page and the same REST API request is sent in the both cases.

**Comment by bartczyz** [comment] 2020-03-11 13:51
Any updates on this one?

**Comment by Chouby** [comment] 2020-03-13 09:31
![](https://github.trello.services/images/mini-trello-icon.png) [Re-usable blocks in Polylang (free)](https://trello.com/c/rBjEqvMp/52-re-usable-blocks-in-polylang-free)

**Comment by bartczyz** [comment] 2020-03-13 09:50
![image](https://user-images.githubusercontent.com/1191500/76609913-74b71f00-6518-11ea-8652-5fdab7ae56bf.png)

**Comment by manooweb** [comment] 2020-03-13 11:16
Hello @bartczyz,

We fixed the problem in Polylang Pro because its a REST API problem. But REST API isn't implemented in Polylang Free version and we have to talk about internally. 

At the moment we haven't taken a decision yet about fixing and how or not fixing this issue with Polylang Free.

Trello is our company private collaborative tool where this kind of discussions takes place.
This card is to remember to us that we have to take a decision.

Regards

**Comment by bartczyz** [comment] 2020-03-13 11:17
@manooweb I'm using PRO version, but haven't noticed any new releases?

**Comment by manooweb** [comment] 2020-03-13 11:25
A [2.7 beta](https://polylang.pro/polylang-2-7-introduces-a-setup-wizard/) has been released on Monday March 9th which doesn't include this fix because we haven't taken a decision yet about Polylang Free version.

**Closed** 2020-03-16 08:09 UTC
Labels: Pro, bug

**Comment by strarsis** [comment] 2020-04-06 17:06
@manooweb, @Chouby: It would be great if Polylang could add support for reusable blocks in the Free version, too. In the current state the reusable blocks aren't even rendered, even with a language set.

**Comment by gmmedia** [comment] 2020-09-13 15:28
I don't think Polylang will win, if we have to decide between reusable block and Polylang. Never block a core feature.

**Comment by strarsis** [comment] 2020-09-13 15:57
@gmmedia: I agree that translatable Gutenberg blocks are indeed a game changer and extremely useful.
So often in the past I needed a partial translation of a large page.

We shouldn't forget though that Polylang is the only plugin that offers so many features in its free version.
There are no (to my knowledge) free plugins yet for translating Gutenberg blocks, and Polylang would be the natural candidate.
