### ISSUE TITLE
Tags disappear when post saved/published/updated.

### ISSUE THREAD

**Issue by FKasa** [polylang/polylang#389] opened 2019-07-11 14:17 UTC
## Prerequisites
- [x] This is not a usage question.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

- [x] I can reproduce this bug consistently with only Polylang active on a default theme

## Steps to reproduce the issue

1. Write new tag (and click it from the auto-complete).
2. Click save draft/publish/update.
3. All tags disappear

## Expected behavior and actual behavior

By checking with the Chrome Devtools, I conclude this is a server side issue since the post data does contain a tags object element with the correct tags but the server returns an empty array.

I can reproduce this bug consistently with only Polylang active on a default theme

I have been using Polylang reliably on this WP instance since Feb 2019.
Server info: PHP 7.3, WP 5.2.2

**Comment by FKasa** [comment] 2019-09-08 11:03
Changed some code that fixed my issue with tags disappearing. This breaks the tags translation feature but it far better to live without that than to have tags removed on each publish/update. 

Here is what I changed:

file: /wp-content/plugins/polylang/include/model.php
function: get_translated_taxonomies
line: 275
edit:
```php
-			$taxonomies = array( 'category' => 'category', 'post_tag' => 'post_tag' );
+			$taxonomies = array( 'category' => 'category' );
```

There is probably a better fix for this, but I did get any feedback and I could not wait anymore :P

**Comment by Chrystll** [comment] 2019-09-09 15:36
You get this behavior because the support of the REST API is not implemented in Polylang (free), it is only implemented in Polylang Pro. This issue is mentioned just here: [Polylang 2.5 and WordPress 5.0 > What are the known remaining issues with Polylang 2.5?](https://polylang.pro/polylang-2-5-and-wordpress-5-0/).

**Comment by FKasa** [comment] 2019-09-10 15:18
Thank you very much for the feedback Christelle.
Should I expect an update on this some time this year or should I work on a better workaround?

**Comment by adnan-cefalo** [comment] 2019-09-11 04:11
A cleaner way to do your workaround would be:
```
add_action('pll_get_taxonomies', function ( $taxonomies ) {
	unset($taxonomies['post_tag']);
	return $taxonomies;
});
```

in theme's functions.php

**Comment by FKasa** [comment] 2019-09-15 10:55
Thanks Adnan, this seems to work just as well. I should be more practical since the theme I am using is updated a lot less frequently than the polylang plugin. This fix is also easier to apply since it can be done through the admin panel.

Here is a more detailed tutorial of your fix that would be easier for beginners:

- Once logged in to you the admin panel (usualy in yoursite.com/wp-admin/ ), go to Appearance > Theme Editor.
- On the sidebar on the right, on of the first files listed should be 'Theme Functions (functions.php)', click on it to edit it.
- At the end of the file, add the code from Adnan:
```php
add_action('pll_get_taxonomies', function ( $taxonomies ) {
	unset($taxonomies['post_tag']);
	return $taxonomies;
});
```
- don't forget to click on the 'Update File' button!
- Correct me if I am wrong but you have to do this again each time after you update your theme (or until this is solved in polylang).

Both fixes, mine and Adnan's, completely disable polylang interactions with tags, making tags universal (not connected to a language, and not translatable). From my understanding there are two aspects of polylang's interaction with tags:

- the auto-assignment of a tag's language to a tag added when publishing/updating a post.
- on the tags editor page (/wp-admin/edit-tags.php?taxonomy=post_tag) where polylang adds a 'language' field to each tag

I understand that you need the REST API to have the tags works from the post editor.  One thing I am am inclined to believe is that it would be relatively more simple/easy to have the tags editor page work with the language feature without assigning a language to tags when editing posts.

Essentially what I am trying to say is that I think that it would be (relatively) easy to have this:

- add a tag to a post when editing it
- tag is linked to post
- tag is itself not linked to any language
- post language feature still work, as usual
- to assign language to the tag I can go to the tag editor page (/wp-admin/edit-tags.php?taxonomy=post_tag) and do that there (which does not require the REST API, from what I understand)
This basically restores total functionality of polylang regarding tags, it just makes a step manual
I would prefer this alternative compared to having tags disappear when clicking Publish/Update on a post, and I would guess other user would too.

I am new to WP and plugins. I would to know if I am on the right track or if am missing some part of the puzzle.

**Comment by Chouby** [comment] 2019-09-20 15:15
Closing as duplicate of #323

**Closed by Chouby** 2019-09-20 15:15 UTC
Labels: block editor, duplicate

**Comment by FKasa** [comment] 2020-04-11 10:35
I didn't see any update regarding the REST API for 2.7.
Is there anything planned in the roadmap for 2.8 or later?
