### ISSUE TITLE
Add shortcode for language switcher

### ISSUE THREAD

**Issue by strarsis** [polylang/polylang#265] opened 2018-06-19 21:44 UTC
It would be great if Polylang offers a shortcode for a language switcher.

**Comment by Chouby** [comment] 2018-06-21 07:57
Could you please clarify your need? A shortcode is meant to be inserted in a post or page to be replaced by some content. The language switcher is something you want to be visible sitewide, not only in some pages or posts.

**Comment by chesio** [comment] 2018-06-26 15:20
I don't think it would be a good idea to have such shortcode in Polylang. Shortcode handlers should be able to work with only local data (ie. whatever is provided by shortcode attributes and content), because shortcode can be executed "everywhere" and language switcher is by design an element that requires some global data like current language, current post/page id etc.

**Comment by swissspidy** [comment] 2018-07-08 11:51
If anything, I would create a Gutenberg block for that. Given the expansion to site customization with widgets and everything, a language switcher block makes more sense than a non-user-friendly shortcode.

Also, there could be a block visibility option similar to the one for widgets, to only show blocks when viewing the specified language.

Let me know if I could help with that :-)

**Comment by Chouby** [comment] 2018-07-09 16:37
I tend to agree that there are always better solutions than shorcodes.

A Gutenberg block to display the language switcher may be a good idea. However, I don't understand what problem a block visibility option would solve.

**Comment by swissspidy** [comment] 2018-07-27 14:12
> However, I don't understand what problem a block visibility option would solve.

What problem does the widget visibility option solve? :-)

Gutenberg is eventually going to replace widgets and when that happens, it makes sense to keep feature parity between widgets and blocks.

**Comment by Chouby** [comment] 2020-09-29 11:58
Closing this issue as we included a language switcher block in Polylang Pro 2.8, as suggested in https://github.com/polylang/polylang/issues/265#issuecomment-403282266.

**Closed by Chouby** 2020-09-29 11:58 UTC
Labels: wontfix

**Comment by swissspidy** [comment] 2020-09-29 12:04
@Chouby Awesome news! Is a visibility option also in planning?

**Comment by Chouby** [comment] 2020-09-29 14:23
This is our will but will much depends on what possibilities will be offered by WP. As far as I have been told, the current Gütenberg interface breaks our visibility field for legacy widgets. Pinging @manooweb

**Comment by kubiqsk** [comment] 2023-06-02 00:00
There is a simple solution for that (for a few bucks)
https://wp-speedup.eu/shop/wordpress-plugins/pro-plugins/polylang-block-language/
