### ISSUE TITLE
Still a problem with URLs on multisite

### ISSUE THREAD

**Issue by soderlind** [polylang/polylang#1315] opened 2023-07-05 17:27 UTC
## Prerequisites

- [x] This is not a usage question (Those should be directed to the [community supported forum](https://wordpress.org/support/plugin/polylang), unless this is a question about Polylang Pro in which case you should [use the helpdesk](https://polylang.pro/support/)).
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of Polylang and the latest WordPress version.
- [x] This bug happens with only Polylang plugin active
- [x] This bug happens with a default WordPress theme active
- [x] I can reproduce this bug consistently

## Steps to reproduce the issue

1. Activate Polylang 3.4.x on a multisite subsite, where url to a site is `mainsite/subsite1`, `mainsite/subsite2` etc

## Expected behavior and actual behavior

I expect everything to work fine, but:

Looks like this didn't work https://github.com/polylang/polylang/pull/1285

`get_home_url` et al sets an url like `mainsite/subsite/subsite` It should be `mainsite/subsite`.

**Comment by pvert** [comment] 2023-07-05 20:42
Hello, 
same problem for me... 
Still waiting for a reply to my last month ticket : 
[](https://wordpress.org/support/topic/home-url-issue-and-strange-behaviours-since-last-update/#post-16768882 )

Please help us !

**Comment by pvert** [comment] 2023-07-07 15:02
Hello again, 
I made many test today...

In my case, only websites using domain mapping (https://wordpress.org/plugins/wordpress-mu-domain-mapping/)seems to be affected.
I had to disable this extension, which is no more usefull if you only have one url address. 
That's wasn't my case, i had several url/domain name for some site, so i made changes directly in my apache virtualhost on a reverse-proxy, by forcing redirection to the primary url. 

For somes sites, i had to flush permalinks.

Now, it's working...

**Comment by pvert** [comment] 2023-07-11 14:58
Thanks @soderlind , 

I had to change all my sites configuration last friday before going on holidays. 
Some problem still remaining today, i had to work instead going to the beach... 

Using the free version of polylang, I can't be derogatory or pushy, and I thank them for allowing us to use it at no cost.
But please, we'd be grateful to have some information in your blog or in response to the many tickets, it would be useful for all those who are struggling. 

One of my sites used the polylang configuration with two differents domains, www.domain.com (FR) and his translation en.domain.com (EN), EN version was redirected to my main multisite blog (which is a totally different site).  I made regex rewrite rule in my apache config to use polylang with www.domain.com/en/ instead. (I saw too late @soderlind hack)

I just found that answer from polylang to this ticket (https://wordpress.org/support/topic/broken-url-main-page/ ) : 

"Hello,

We have reproduced your issue. This should be fixed in the next release (planned mid July)."


Wait and see what's coming next.

**Comment by Chouby** [comment] 2023-07-17 09:51
@soderlind You checked "The issue still exists against the latest master branch of Polylang and the latest WordPress version." Did you really test with the master branch. We expected that #1300 fixed this issue.

**Comment by Chrystll** [comment] 2023-10-24 07:14
I am closing this ticket as there has been no response from the sender for three months.

**Closed by Chrystll** 2023-10-24 07:14 UTC
Labels: Reporter feedback
