### ISSUE TITLE
PL does not filter posts displayed in admin category and parent post select

### ISSUE THREAD

**Issue by AlexanderBorysenko** [polylang/polylang#963] opened 2022-01-15 14:47 UTC
![image](https://user-images.githubusercontent.com/85223132/149625934-a22408a0-ffca-4d84-92d9-0621c1eb2838.png)

How to prevent such behaviour. I think only terms with same language as post should be in terms select. The same with parent page slect
![image](https://user-images.githubusercontent.com/85223132/149626029-080f55db-c960-4b2a-ba4b-4650f7936ffa.png)

**Comment by Chrystll** [comment] 2022-01-24 09:41
The behavior that you describe is mentioned here:[ Polylang 2.5 and WordPress 5.0 > What are the known remaining issues with Polylang 2.5?](https://polylang.pro/polylang-2-5-and-wordpress-5-0/). In fact it doesn't work with Polylang because the REST API (that the block editor used) compatibility is only implemented in Polylang Pro.

**Comment by Chouby** [comment] 2022-02-02 09:09
Duplicate of #323

**Closed by Chouby** 2022-02-02 09:09 UTC
Labels: duplicate
