### ISSUE TITLE
Share slugs feature doesn't work for terms

### ISSUE THREAD

**Issue by chesio** [polylang/polylang#73] opened 2016-12-07 23:02 UTC
Hi Chouby,

When I create term that has identical slug in all languages and try to view term page in front-end, I always get redirected to default language page for that term in all other languages (by PLL_Frontend_Filters_Links::check_canonical_url() method).

I have confirmed this problem on a test site with WordPress 4.7, TwentyFifteen theme and no other plugin except for Polylang Pro 2.0.10 (no CPTs are involved, this problem happens with core tags taxonomy). The backend language is different than languages configured in Polylang, but I guess this doesn't matter.

I also created a page with the same slug in all languages and this works just fine, so the problem seems related to terms only.

**Comment by Chouby** [comment] 2016-12-08 07:19
Hi,

I can reproduce. It looks like the issue is introduced by WP 4.7

**Comment by Chouby** [comment] 2016-12-08 07:28
Can you go in modules/share-slug/frontend-share-term-slug.php and change this:

{{{
@@ -41,6 +41,11 @@
 			// PHP 7 does not include call_user_func
 			$n = version_compare( PHP_VERSION, '7', '>=' ) ? 3 : 4;
 
+			// FIXME Backward compatibility with WP < 4.7
+			if ( version_compare( $GLOBALS['wp_version'], '4.7', '>=' ) ) {
+				$n++; // Since WP 4.7 get_term_by calls get_terms
+			}
+
 			// The filter get_term is the same in get_term and get_term_by, moreover we need to know if we get_term_by slug
 			if ( isset( $traces[ $n ]['function'], $traces[ $n ]['args'][0] ) && 'get_term_by' === $traces[ $n ]['function'] && 'slug' === $traces[ $n ]['args'][0] ) {
 				$join = "INNER JOIN $wpdb->term_taxonomy AS tt ON t.term_id = tt.term_id" . $this->model->term->join_clause();
}}}

**Comment by chesio** [comment] 2016-12-08 08:37
Thanks, your patch solves the problem!

Btw. the get_term function is... crazy :) I never saw someone working with function call stack this way :)

**Comment by Chouby** [comment] 2016-12-08 09:23
Yes. I am not enchanted to do such things. Sometimes we have to found (weird) workarounds when we don't have the right filter at the right place.

The patch will be introduced in 2.0.11  to be released next week.

**Closed by Chouby** 2016-12-08 09:23 UTC
Labels: Pro

**Comment by chesio** [comment] 2016-12-08 10:13
> Sometimes we have to found (weird) workarounds when we don't have the right filter at the right place.

Yeah, I totally understand.

**Comment by Chouby** [comment] 2016-12-08 11:15
I did not understand how our tests could miss that issue. Now I know: https://core.trac.wordpress.org/ticket/21760#comment:116
Late change done just before the release :/
