### ISSUE TITLE
Unable to save Categories

### ISSUE THREAD

**Issue by hutber** [polylang/polylang#413] opened 2019-10-01 22:34 UTC
I have checked everything from the list and only have the `Polylang` plugin active. 

## Steps to reproduce the issue
I wish there was a simply way for me to reproduce this error but I am not sure there is, simply because this feels like a very unusual bespoke error. However I can reproduce it very easily with my current setup.
1. Active Polylang
2. Add categories for each lang (eng, esp)
3. Add some english categories 
4. Select these categories to an english post
5. Hit `Update`
6. Watch your categories disappear 
7. Reload page
8. Original categories before update are back.
9. Deactivate Polylang
10. Select a new category and save
11. reload page, new category is selected
12. Repeat steps and categories selected while the plugin was inactive are properly saved.

In image form:
**Initial categories on every single page reload:**
![image](https://user-images.githubusercontent.com/1344898/66005396-36b2cb00-e4a3-11e9-96ad-6ce19e4c9a03.png)
**Select other categories**
![image](https://user-images.githubusercontent.com/1344898/66005423-52b66c80-e4a3-11e9-8f3e-d4e39f1e63ff.png)
**Hit Update - All categories deslected**
![image](https://user-images.githubusercontent.com/1344898/66005460-6f52a480-e4a3-11e9-98e3-92128c4ef28b.png)
![image](https://user-images.githubusercontent.com/1344898/66005437-5c3fd480-e4a3-11e9-94df-01018ba77cb4.png)
**Reload page**
![image](https://user-images.githubusercontent.com/1344898/66005396-36b2cb00-e4a3-11e9-96ad-6ce19e4c9a03.png)

**Deactivate Polylang Select a new category and update** 
![image](https://user-images.githubusercontent.com/1344898/66005508-a032d980-e4a3-11e9-8018-8010d78c4dea.png)
![image](https://user-images.githubusercontent.com/1344898/66005607-ebe58300-e4a3-11e9-9227-bfb97a0f2fdf.png)

## Expected behavior and actual behavior

I would expect the categories to be saved

**Comment by Chouby** [comment] 2019-10-04 11:07
This is a known issue with the block editor that we have aknowledged when we released Polylang 2.5. See https://polylang.pro/polylang-2-5-and-wordpress-5-0/. When you create a new category from the block editor, it is correctly saved (you can see it in Posts > Categories) but not assigned a language (that's why you don't see it in the editor sidebar as they are filtered according to the current post language). This is because we did not include any REST API Support in Polylang.

You have 3 options:
* Use the classic editor. It will work as you expect.
* Create your categories in Posts > Categories instead of the editor.
* Switch to Polylang Pro which supports the REST API.

Closing as duplicate of #323

**Closed** 2019-10-04 11:08 UTC
Labels: duplicate
