### ISSUE TITLE
Using Polylang 2.2 cause immense front-end slowdown

### ISSUE THREAD

**Issue by Razerwire** [polylang/polylang#170] opened 2017-08-27 17:50 UTC
Hi,
Since updating to polylang 2.2, our WordPress based website (running WordPress 4.8.1 and the Customizr theme Version: 4.0.5), polylang causes huge delays.

TTFB has gone from 800ms to about 20 seconds! When disabling polylang site speed is normal again. 

If you need more info please let me know.

**Comment by Chouby** [comment] 2017-08-28 07:02
I am aware of this issue as it has been reported on the support forum. However, for the past week, no progress has been made because I don't get correct answers to my questions.

If you ready to spend time to help solving this issue, I'll do my best. Otherwise you can close the issue.

The first steps have probably not been done since you did filled the issue template.
1. Did you test against the latest master branch?
2. Does this happen with only Polylang and Twenty Seventen? If no wan you identify the conflicting plugin or theme?

**Comment by Razerwire** [comment] 2017-08-28 07:48
I'll try and help out.
I'll test against master branch and try to identify any conflicting plugin or theme, give me a couple of days and i´ll get back to you.

**Comment by alfredo49** [comment] 2017-08-29 08:16
I have same problem, Polylang 2.1 works perfect, but Polylang 2.2 causes frontend super slow.. (three times more, 7s to 25s)

IMPORTANT: Only happens with PhP 5.6, in PhP 7 all versions are fast. But my web must have in php 5.6

i have installed master but problem isnt solved :(.

i had to go back to polylang 2.1 while the problem is solved..

Thxs

**Comment by Chouby** [comment] 2017-08-29 10:22
@alfredo49 For what I read, it is not theme conflict but could be a plugin conflict if you did not deactivated them all. Your information about the PHP version is interesting. Phpunit tests are running on PHP 5.6 but they don't help much in detecting any performance issue. 

Could you activate the plugin https://wordpress.org/plugins/theme-plugin-profiler/ on your test site? This will display a long table with function execution times. I am interested in the slow functions.

**Comment by alfredo49** [comment] 2017-08-29 10:41
Hi @Chouby , i just installed the plugin but in front end pages only return this...


Function Name | Execution calls | Total execution time | Execution time per call
include_once | 1 | 0.0002923012 | 0.0002923012
Total | 1 | 0.0002923012 | 0.0002923012

**Comment by Chouby** [comment] 2017-08-29 11:54
Obviously, the plugin did not work on your site :/. Hopefully someone else will get a better report.

**Comment by Chouby** [comment] 2017-08-29 12:05
Are you able to install XDebug on your test server? See https://codex.wordpress.org/Testing_WordPress_Performance#Xdebug
If this is possible and you can upload a cachegrind file, this would help a lot.

**Comment by alfredo49** [comment] 2017-08-29 12:32
Hi @Chouby 

I think that i found the issue, i try in several pages with Polylang installed.

I have sites with Avada WordPress Theme , this sites have the issue.
I have other with HTML5 Blank Page (Custom) , this also have the issue.

In **Polylang settings => URL modifications => The language is set from content** 

If you choose this options the front pages have this issue , the themes that have the issue runs very slowly, but if you choose

**The language is set from the directory name in pretty permalinks** , all runs OK

I attach you a video in a zip, you can watch the issue . Also happens with all the plugins deactivated except polylang
[polylang.zip](https://github.com/polylang/polylang/files/1260240/polylang.zip)

**Comment by Razerwire** [comment] 2017-08-29 14:51
Okay, 
1. I've tested master-branch and the issue is still present.
2. I've disabled all plugins except for polylang and the issue is still present.

**Comment by Razerwire** [comment] 2017-08-29 14:56
3. I've tried T&P Profiler but it doesn't give useful info.

**Comment by Chouby** [comment] 2017-08-29 18:04
@alfredo49 

If I summarize your results.
* The PHP version finally does not seem to be tehe cause of the issue.
* The issue appears only when the language is from the content and the site language is Spanish.

Is that right?
I will try to follow this path.

@Razerwire 
2. Did you switch to a default theme too? That would be the first time that the issue is reported with Polylang alone.
3. Did you check the “execute plugin” option and choose “total time” for order in the plugin settings. Also did you make the test with Twenty Sixteen? I noticed that there is a display issue with Twenty Seventeen.

**Comment by Razerwire** [comment] 2017-08-29 18:11
>The PHP version finally does not seem to be tehe cause of the issue.

I've tried both PHP 5.6 and PHP 7, both versions are affected


>Did you switch to a default theme too? That would be the first time that the issue is reported with Polylang alone.

No i'll try that next 
> Did you check the “execute plugin” option and choose “total time” for order in the plugin settings. 

I'll re-check and get back to you on this.

> Also did you make the test with Twenty Sixteen?  I noticed that there is a display issue with Twenty Seventeen.

No, i guess if there's a display issue it needs a separate bug to be tracked.

**Comment by Razerwire** [comment] 2017-08-29 18:21
I've tried both "twenty sixteen" and "Twenty seventeen" theme's both theme's are fast with the polylang plugin enabled, although the whole site is a mess with those theme's so that could be the cause of the problem not showing

**Comment by Razerwire** [comment] 2017-08-29 18:25
![image](https://user-images.githubusercontent.com/14997009/29837370-38f8f10a-8cf8-11e7-8e6e-26b675c7254a.png)

**Comment by Chouby** [comment] 2017-08-29 18:30
It's strange that the profiler plugin displays only one call for both of you (the output was more interesting in my tests).

Just to cross check with the results of @alfredo49, what are your url modifications in Polylang settings and what is your site's language in Settings > General?

**Comment by alfredo49** [comment] 2017-08-29 18:30
@Chouby 

- In one of my wordpress installations (i dont know if happens with other wordpress themes), issue is solved updating php 5.6 to php 7. In the other hand, in Avada theme (last version) the issue happens with any php version.

- Yes but the issue happens always ,happens in the main language pages (spanish) and in the translation pages (english) . The front site is slowly in all the pages.. 

In both cases:

Polylang settings in "The language is set from content" and spanish language in wordpress settings, with other combinations runs OK

**Comment by Razerwire** [comment] 2017-08-29 19:01
> Just to cross check with the results of @alfredo49, what are your url modifications in Polylang settings and what is your site's language in Settings > General?

The language is set from content for me as well.
Language in Settings > General is set to "Nederlands" (Dutch) 
Polylang is set to translate to Spanish
"Hide URL Language information for the standard language" is checked;
"Remove /language/ permalinks" is selected;
"The front page-url contains the language-code instead of the page name or page-id" is selected.

**Comment by alfredo49** [comment] 2017-08-30 07:31
In my case: 

1) Changing the default Wordpress language (in wordpress settings) to another language. 
OR
2) In polylang settings change "The language is set from content" to "The language is set from the directory name in pretty permalinks ". 

The problem is solved, using one of this methods... 

It isnt a solution for me, but maybe can help to @Chouby to identify the problem

**Comment by alfredo49** [comment] 2017-08-30 09:18
Also i have made it work Profile Plugin, all funcions are aprox. 0 s except these:

Function Name | Execution calls | Total execution time | Execution time per call
include_once | 2 | 5.0861971378 | 2.5430985689
create_function | 1 | 8.5353553295 | 8.5353553295

**Closed** 2017-08-30 09:19 UTC
Labels: Reporter feedback

**Comment by Chouby** [comment] 2017-08-30 09:21
Thanks to both of you for your help!  Your tests results helped me to reproduce teh issue and find out how to solve it. May I ask you to make a final check with the current master branch?

**Comment by alfredo49** [comment] 2017-08-30 09:29
Thxs a lot! in my case the new master branch solved the issue in all of my sites!! 👍

**Comment by Razerwire** [comment] 2017-08-30 09:32
Can confirm fix in master branch!

**Comment by Chouby** [comment] 2017-08-30 11:25
Thank again. This is now in version 2.2.1.

**Comment by tlamiczka** [comment] 2018-11-27 10:06
Currently - I have similar problem too. Polylang plugin makes the page load 15 seconds instead of 3 seconds.
Wordpress 4.9.8, Polylang 2.4.1, theme Customify 0.2.5

It seems it has some problem with speed of detecting - when I disabled "Detect browser language", the speed massively improved. 
Using for example https://www.giftofspeed.com/ - it seems both languages (ENG, CZ) were loaded when the detection was turned on.
