### ISSUE TITLE
String translation not working if languages have same order number

### ISSUE THREAD

**Issue by mikkohopia** [polylang/polylang#109] opened 2017-03-16 06:37 UTC
If there is two languages with same order number (e.g. zero), string translations does not work. After saving the string nothing happens. When one of the languages order is set to one (1) string translations work normally.

WP 4.7.3
Polylang 2.1.2

**Comment by Chouby** [comment] 2017-03-16 19:19
It works for me. Are you able to reproduce on a fresh install?

**Comment by mikkohopia** [comment] 2017-03-16 19:58
You are correct, on fresh install it works. Probably issue with some other plugin. I will let you know if I am able to reproduce this later. However, string translations started to work after I updated the order value of the language.

**Comment by Chouby** [comment] 2017-03-20 11:59
OK. I close the issue for now but don't hesitate to comment on it if you can reproduce later (I also read closed issues).

**Closed by Chouby** 2017-03-20 11:59 UTC
